name: Nessus Scan Pipeline

on:
  push:
    branches:
      - main  

jobs:
  scan:
    runs-on: ubuntu-latest 

    steps:      
      - name: Checkout code
        uses: actions/checkout@v3
     
      - name: Update and install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get upgrade -y
          sudo apt-get install -y --fix-broken docker.io jq curl
     
      - name: Run Nessus scan script
        run: |
          # Lancer le script Bash
          chmod +x ./run_nessus_scan.sh
          ./run_nessus_scan.sh

      - name: Upload scan report
        uses: actions/upload-artifact@v3
        with:
          name: nessus-scan-report
          path: scan_report.html
